### ISSUE TITLE
Updating layer metadata fails with timeout

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#107]
Updating a layer's metadata information from the main GeoNode UI is not working. After some time, GeoNode shows as timeout error (as depicted below)

![Screenshot from 2020-10-01 14-36-16](https://user-images.githubusercontent.com/732010/94816409-b1366380-03f3-11eb-9758-02ac4d3f297a.png)

**Comment by lucernae** [comment]
Same problem with #108 , caused by failed layer thumbnail saves
