### ISSUE TITLE
Updating layer thumbnail fails with timeout

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#108]
Similarly to #107, when trying to update a layer's thumbnail GeoNode idles around for a bit and finally returns an error message

![Screenshot from 2020-10-01 14-40-33](https://user-images.githubusercontent.com/732010/94816702-17bb8180-03f4-11eb-8985-d74d3d174953.png)

**Comment by lucernae** [comment]
For some reason the internal route of GeoServer doesn't accept the thumbnail request.
I switch it to the public route as a fix
