### ISSUE TITLE
GeoNode user menu is displayed below layer map

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#111]
The GeoNode user menu is displayed below the map

![Screenshot from 2020-10-01 16-07-35](https://user-images.githubusercontent.com/732010/94827408-4ccdd100-0400-11eb-9cf2-94fc77b88761.png)

**Comment by ricardogsilva** [comment]
Even after samweli's fix, (which I tested locally and seemed to work OK) we are still having this issue both on staging and on prod environments (see below screenshot)

Samweli's fix is included in the latest version of the images that we have running in these envs. I also checked that the css file present on the django `STATIC_ROOT` has the css `high-index` class that samweli has implemented.

Could this be some sort of caching error?

Assigning this to @lucernae

**Comment by lucernae** [comment]
ok. I'm not aware of this issue, but I can check it quickly

**Comment by lucernae** [comment]
So, @ricardogsilva  as a wrap up. I was only able to try this a bit today, but it seems I can't replicate the issue.
I also check the image is latest and compare the hash, same with the latest push. It also present in the html in the url you posted above in the screenshots.
So, it maybe a caching error (the css), or perhaps you view it when the new image has not been deployed. I do admit that the deployment is still manual now.

**Comment by ricardogsilva** [comment]
Seems to be working fine now. @lucernae if you could not replicate it then it probably was a caching issue on my side. Closing the issue.

**Comment by ricardogsilva** [comment]
just some final proof that it works here:

![Screenshot from 2020-10-19 10-57-24](https://user-images.githubusercontent.com/732010/96430612-4b6f1780-11fa-11eb-8b3d-d738ff0ab41a.png)
