### ISSUE TITLE
cannot publish layers that come from DB on production environment

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#121]
There seems to be an error with the GeoServer instance on the production environment whereby it is not possible to publish layers that come from the PostGIS DB. Note that the same procedure works OK on staging, as demonstrated by the two short videos below. The whole procedure is:

1. login to geonode with suitable user credentials

1. access the `/geoserver` page and login via Oauth, using the user that has just been logged in to geonode

1. add a new layer on GeoServer

    1. choose a PostGIS store - for a reproducible test case please select the `ppd:dominode_db_ppd` store)

    1. choose a table from the PostGIS db - for a reproducible test case please select the `ppd_building-footprints-roseau_v1.0.0` table (might need to got to the next page of tables on production env)

    1. in the _Edit layer_ page, go to _Bounding boxes_ and  compute both the native and the lat/lon bboxes

1. Go to _Layer Preview_ section and try to preview the newly added layer with the _OpenLayers_ common format

The expected result would be that a new browser tab is opened and the layer is correctly shown on an openlayers map. The staging environment indeed works as expected. However, on prod, GeoServer sends back the following Exception Report:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "https://prod.dominode.piensa.co/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd?access_token=n8l1rDsfEG3ASShwDTtgsn4n9IjwHU"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.RuntimeException: org.xml.sax.SAXParseException; Premature end of file.
org.xml.sax.SAXParseException; Premature end of file.
Premature end of file.
</ServiceException></ServiceExceptionReport>
``` 

#### staging environment video (works OK)
![staging_ok](https://user-images.githubusercontent.com/732010/95490646-69ce4b00-0990-11eb-88b5-e67df59a43e5.gif)

#### production environment (DOES NOT WORK)
![production_not_ok](https://user-images.githubusercontent.com/732010/95490681-794d9400-0990-11eb-81f2-aa5e1b18c6c8.gif)

**Comment by lucernae** [comment]
I'm just going to report my finding here as I can't pinpoint the exact cause.

What I first noticed from the GIF is, in the prod environment the layer attributes at the bottom seems to be duplicated.

So I tried to recreate the layer definition, but it ends up being duplicated all the same.
Then, I tried to create a different store with the database owner credentials, and the layer works. So it's not the table's problems.
Next, I tried to create a different store with the `ppd_geoserver` credentials, the same one used by the `dominode_db_ppd` store. The layer works

I then compare the settings of both store and found out that most default settings of `dominode_db_ppd` store is empty, even the schema name too. I checked that other store is like that as well.

So I delete `dominode_db_ppd` store and recreate it using UI. I proceed to publish the layer. Then the layer works.

My guess is, some of the default settings are needed to be defined in the xml file itself. I tried to particularly delete the schema name, like other store, then my layer doesn't work. But If I create layer in other store, it works even if they don't have the schema name defined. So I'm pretty confused myself.

Here's the screenshot of the default settings created from the UI vs what we already have:

![image](https://user-images.githubusercontent.com/831865/95733305-25062500-0cac-11eb-9a87-1ea59ea1ce5f.png)

![image](https://user-images.githubusercontent.com/831865/95733342-351e0480-0cac-11eb-985f-ac77ffb12e1d.png)

**Comment by ricardogsilva** [comment]
After deleting and recreating all stores and workspaces by using the dominode-bootstrapper I was still having this error.

Then I found a stackoverflow thread were someone was complaining about duplicate featuretypes being shown on the layer edit page of GeoServer:

https://gis.stackexchange.com/q/141996

It turns out there was a [GeoTools bug](https://osgeo-org.atlassian.net/browse/GEOT-2833) which apparently did not get resolved 100% and is what is causing our problem.

The layer in question `ppd_building-footprints-roseau_v1.0.0` was actually present in both the `public` and the `ppd_staging` schemas. This somehow confuses GeoServer and this confusion manifests in several ways, such as showing duplicate feature types and also being unable to use the layer for WMS, etc.

I think the most secure solution is to be sure to always specify the `public` schema when creating new stores - even if the geoserver users that we are using to access the DB don't really have permission to access other schemas.
