### ISSUE TITLE
design workflow for publishing topomaps

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#127]
We need a clear workflow for dealing with the publication and distribution of topomaps

**Comment by ricardogsilva** [comment]
Let's implement a workflow as depicted by the diagram below:

![topomap-publication](https://user-images.githubusercontent.com/732010/96460182-dbbd5480-121a-11eb-8500-fad415de66b4.png)


The workflow has the following steps:

1. `lsd_user` works on topomap series until it is ready to be published;
2. after a review, `lsd_editor` saves the QGIS project in the `lsd_topomaps` schema, with a proper name and version. This is done by leveraging a custom Processing model;
3. Using the atlas functionality of QGIS, suitable GeoPDF files are generated for each sheet in the topomap series;
4. Each sheet is validated by performing an attentive inspection of the generated output and by leveraging the QGIS Dataset QA Workbench plugin;
5. Sheets are uploaded to a private minIO bucket at `/lsd-topomaps/v{version}/series-{scale}`;
6. An index sheet layer for the series is generated, containing suitable hyperlinks in a new `download_url` column. This is done by means of a custom Processing model;
7. The new index sheet is then validated by leveraging the QGIS Dataset QA Workbench plugin;
8. Index sheet is then moved to the DB's `public` schema;
9. Index sheet is published on GeoServer;
10. Index sheet is published on GeoNode;
11. Metadata record for index sheet is finalized and it is made public - note that the index sheet layer shall be public, but individual topomap sheets are only downloadable by users with suitable authorization (see below);

As for the download of topomaps, they shall be mediated by a new custom geonode application, `dominode_topomaps`.

This custom app shall have the following routes:

- `/` - shows a list of published topomap series, along with some general info on each. It also features a link to each published index sheet's details page. This information is generated dynamically by inspecting the list of layers already publsihed on GeoNode. This means that as soon as an index sheet layer is removed from GeoNode (for example, an old version of the topomap, which is no longer valid) it will also stop showing here

- `/v{version}/series-{scale}/` - shows info on the concrete topomap series and also has a list of links to individual sheets

- `/v{version}/series-{scale}/{sheet-id}` - shows info about the sheet and features links for a) downloading the sheet as a GeoPDF file b) the parent topomap series

Downloading individual map sheets is only allowed for users that have the `topomaps:download_sheet` permission. This permission shall be granted to all users that are members of the `topomap-downloader` group.

**Comment by lucernae** [comment]
Asking for confirmation:

- Does the available bucket only comes from `lsd-topomaps`? No other groups will publish topomaps?

**Comment by ricardogsilva** [comment]
> Does the available bucket only comes from lsd-topomaps? No other groups will publish topomaps?

yes, the only department that shall be allowed to distribute published topomaps is LSD (Lands and Surveys Department) - this is the department with the authority to publish official topomaps

**Comment by ricardogsilva** [comment]
@lucernae I've fixed dominodeorg/dominode-bootstrapper#18, which adds a the creation of a new `lsd-topomaps` bucket to the dominode-bootstrapper. I'll soon incorporate this into a new dominode-bootstrapper docker image and in addition to that I'll make the necessary changes to prod to have this bucket created there
