### ISSUE TITLE
finalise cartographic standards

### ISSUE THREAD

**Issue by gubuntu** [dominodeorg/dominode#17]
https://docs.google.com/document/d/1-Y0MhmB4eQ6VeaV8d3UrmCxRMg24hzbdRIbswzpW0kc/edit#

**Comment by ricardogsilva** [comment]
We received some comments from the PCU about this. Find them here (section D10):

https://drive.google.com/drive/u/1/folders/1xRv9zXrnQ691ZtYRlZIApNsYiFmjYAAd

**Comment by zacharlie** [comment]
New cartographics standards document has been developed:

https://docs.google.com/document/d/1rZMG8GGtyIqVZAFHqEUXnbxFRI3E5LPqe3jaVkG0-bk
