### ISSUE TITLE
All rasters need to be a COG

### ISSUE THREAD

**Issue by LunaAsefaw** [dominodeorg/dominode#174]
All rasters need to be Cloud Optimized GeoTIFF (COG) in the same object store.
This can be done when we have access to data. Tests need to be done on dummy data in the meantime

**Comment by vermeulendivan** [comment]
This is in progress. Tif files and ESRI grid rasters needs to be converted. Some data needs to be mosaicked as well as asked by the client

**Comment by LunaAsefaw** [comment]
This ticket has been broken down into smaller tickets
