### ISSUE TITLE
Going through all the folders and classifying work that needs to be done

### ISSUE THREAD

**Issue by LunaAsefaw** [dominodeorg/dominode#179]
There is a tremendous amount of data on the minio-data folder and they all need different types of processing. We need to go through each folder and classify what kind of processing needs to be done.
Create a ticket for each one

**Comment by vermeulendivan** [comment]
Mostly done. A lot of data and slow over the internet and ssh

**Comment by vermeulendivan** [comment]
My work on making notes of the folders and where data is and what formats we will be processing is done.
