### ISSUE TITLE
Running out of space on server

### ISSUE THREAD

**Issue by EliVolsch** [dominodeorg/dominode#192]
The current save location is running out of space. We do not want to remove the original data from the system, but it is rapidly running out of space. Can you increase the space available?

**Comment by EliVolsch** [comment]
In communications with Ariel he mentioned he will be able to provision more storage next week

**Comment by LunaAsefaw** [comment]
I will be deleting processed files since Ariel has mirrored the files

**Comment by EliVolsch** [comment]
Additional storage space has been requested from ITC. 

Ariel has moved some files to an additional drive to free up space.
