### ISSUE TITLE
set up MinIO access acccording to permission matrix

### ISSUE THREAD

**Issue by gubuntu** [dominodeorg/dominode#25]

**Comment by ricardogsilva** [comment]
I've started analyzing the required permissions, similarly to the work done for the main postgis DB. Using this spreadsheet

https://docs.google.com/spreadsheets/d/1uiuey2w4IvCNtNK0rV2Z3e5IOk0TsbGrkQit9Cdic0o/edit#gid=643393779

The plan is to produce a bootstrap script for minIO access permissions that creates all necessary groups and policies.
