### ISSUE TITLE
Skin GeoNode

### ISSUE THREAD

**Issue by gubuntu** [dominodeorg/dominode#29]
Use elements from dominode.dm to skin the new one in the current best practice way using the same logo and colour scheme.

We just want a basic skin for now, not too much effort.

**Comment by gubuntu** [comment]
@lucernae @ricardogsilva please maintain the project board and issues e.g. this should be closed with an explanation

**Comment by ricardogsilva** [comment]
@lucernae can you give me a brief description on how this was implemented and in what way is it being carried over in k8s. I think this is probably a similar explanation to the ones requested in #47 and #46, so you may group them together in a comment on one of these issues if you prefer.

Can we close this issue @lucernae? If so, please do

**Comment by lucernae** [comment]
For future reference, we skin geonode using geonode-project and stored the module in this repo.
