### ISSUE TITLE
Document procedure for accessing minio on staging environment

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#34]
Write a short section on our internal docs detailing how to access, use and confgure the minio instance that is currently deployed to staging environment

https://docs.google.com/document/d/1eqjlYGl1s9GJiq6a7Sbh6sBotU101Jc0gtpvl3GDgxM/edit#heading=h.tza7cfsvmcox

**Comment by ricardogsilva** [comment]
@ingenieroariel 
What is the status on this?

**Comment by ingenieroariel** [comment]
I have moved the minio server to one with mirrored 8TB disks and tested
access from Windows. I'll put the instructions on a private document and
link here.
