### ISSUE TITLE
Document procedure for accessing the relevant infrastructure on the staging environment

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#35]
Write a short guide on how to connect to the staging environment

Please include:

-  How to use rancher in order to access the environment
-  How to use kubectl to monitor the cluster (with rancher and with a local terminal)
-  How to connect via SSH
-  How to access the various databases (geonode, geoserver, metadata)

**Comment by gubuntu** [comment]
The document already exists and just needs to be updated. See #19

**Comment by lucernae** [comment]
@gubuntu @ricardogsilva, should the document #19 also contains Credentials for SSH/database connections? Or we make credentials as separate document and refer to it from the docs by sections to refer to the secret?
