### ISSUE TITLE
Deploy stack to production environment

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#36]
After #33 is done, or while it is being finalized we need to deploy the tech stack into the production environment.

-  [x] - Rancher and Kubernetes cluster configuration

-  [x] - minIO
   -  [x] - Setup a mount for raster data. It should be properly structured in order to offer dedicated areas for each stakeholder, including a `production` and a `staging` area for each, as specified in #25 
   -  [x] - Setup a mount for the GeoServer data dir too
   -  [x] - Setup a mount for the django media dir too (to store uploaded user profile pictures)

-  [x] - Install PostGIS data DB
   -  [x] - Configure appropriate schemas for each stakeholder, including those for `production` and `staging` as specified in #26 

-  [x] - Install and configure GeoServer

-  [ ] - ~Install and configure Geonetwork - This will also require a DB for storage of metadata records~

-  [x] - Install and configure Geonode
   -  [x] - Also needs a DB
   -  [ ] - ~Setup Geonetwork as the metadata catalogue~

**Comment by ricardogsilva** [comment]
@ingenieroariel 
What is the status on this?

**Comment by ingenieroariel** [comment]
We were blocked by access to the production environment but that was fixed
on Friday last week.
