### ISSUE TITLE
Determine which layers are to be used for the national topographic maps

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#37]
The topo maps need to contain similar themes to the ones used by UK's Ordnance Survey agency in 1991, of which a picture is available on the first mission report

https://docs.google.com/document/d/1-tdcNiT-hWiK3QvuMJCCUGh4xTtLXV5fW1ugxN0Ln3M/edit#heading=h.rl7kdm1pjk0

We need to understand which layers are needed and how to use them in order to produce a topographic map of similar quality

**Comment by ricardogsilva** [comment]
@NyakudyaA 

We have some data in the staging environment which you may use in order to start identifying pre-existing layers. Most of these came from the older DomiNode production instance (which this project will be replacing) so they are likely to still be relevant.

There is a [google doc] that has relevant credentials for accessing the staging environment. In there you will find credentials for the _Geoserver geonode data store user (copy of production instance)_. With these you should be able to connect to the DB from your local QGIS desktop and load the layers.

I believe some of the layers that will be necessary for the topo maps should be there.

[google doc]: https://docs.google.com/document/d/1eqjlYGl1s9GJiq6a7Sbh6sBotU101Jc0gtpvl3GDgxM

**Comment by zacharlie** [comment]
I have begun an audit of the data available from the staging environment and documenting data suitability for topographic map production. There is a [report document available on Google Docs](https://docs.google.com/document/d/1fucFDfhifz1nXZYjEAAULGh-3SsVEfj2g_VVoo2y-8M/edit?usp=sharing) which provides an overview on the progress made as well as [a data audit spreadsheet](https://docs.google.com/spreadsheets/d/1kwdn5VLnAT_s1QeqVTitKclqOiRxg0RFu_B2r9UNgys/edit?usp=sharing) which details the status of each feature available from the staging environment and any issues encountered with it's use.

**Comment by ricardogsilva** [comment]
@zacharlie 

I think this task is completed, right? If so, please close this issue

**Comment by zacharlie** [comment]
Task completed in line with commentary available in the [Topo Data Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1uiuey2w4IvCNtNK0rV2Z3e5IOk0TsbGrkQit9Cdic0o/edit?usp=sharing). A "50K Data" sheet was added indicating items from the data catalog (along with their relevant identifier)
