### ISSUE TITLE
Map topo styles from gh:kartoza/topostyle to Dominica layers

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#38]
We will be using the styling work done in [topostyle] as a starting point for styling the layers used in the Dominica topo maps.

For this we need to map the topostyle styles to the layers determined in #37. We will also need to tweak the styles as appropriate.

[topostyle]: https://github.com/kartoza/topostyle

**Comment by zacharlie** [comment]
As outlined in #37 I have begun developing a topographic map using the available data from the staging environment. I am developing the map thematic in a manner that emulates the available historical maps oulined in the [report document](https://docs.google.com/document/d/1fucFDfhifz1nXZYjEAAULGh-3SsVEfj2g_VVoo2y-8M/edit?usp=sharing), as matching the topostyles project to the existing schema and overcoming issues as outlined [in the data audit spreadsheet](https://docs.google.com/spreadsheets/d/1kwdn5VLnAT_s1QeqVTitKclqOiRxg0RFu_B2r9UNgys/edit?usp=sharing) may delay progress. The intended workflow process going forward is to use this map as a base project which is then refined from the more advanced styling options available from the topostyles project and develop a common thematic which may be utilised across all of the topological map series.

**Comment by zacharlie** [comment]
@ricardogsilva  I have completed the migration of these styles for the available data, however there are multiple issues that need to be resolved (with the underlying data, styles and layouts) which I will create individual issues for. Can we mark this as closed?

**Comment by ricardogsilva** [comment]
I assume these will be included in your pending PR #58, right?

If so, please link this issue in the PR and it shall be closed automatically when the PR is merged. If not, then go ahead and close it then
