### ISSUE TITLE
Implement a web interface for the download of topo maps

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#41]
We need to implement a web interface for the public to access the generated topo maps. This might be subject to data distribution policies and/or some monetization

**Comment by gubuntu** [comment]
this could be an OTS app like LizMap for on-demand generation. 

For simple download of pre-rendered pdfs a link in a metadata document describing the map should be sufficient.

**Comment by ricardogsilva** [comment]
tracking this in #128 now, so closing this one
