### ISSUE TITLE
Load all vector layers used in the topo maps into PostGIS

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#42]
All layers used in the production of the topo maps are priorities to be available in PostGIS to support topo maps in QGIS 

The layers might well be published in GeoServer as well (to provide web service endpoints for general users)

**Comment by gubuntu** [comment]
@ricardogsilva we are producing the topo maps in QGIS with QGIs styling and QGIS layouts. 

while the layers might well be published in GeoServer as well (to provide web service endpoints for general users) this ticket needs revisiting

**Comment by gubuntu** [comment]
subset of #22

**Comment by ricardogsilva** [comment]
all layers required for our initial topomap release are now in the production DB, so closing this
