### ISSUE TITLE
Provide an online basemap for the general public, based on OSM data

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#43]
This is still to be better described

**Comment by gubuntu** [comment]
@ricardogsilva where is this requirement specified? I'm not aware of it and we haven't budgeted to produce a basemap

**Comment by ricardogsilva** [comment]
I've been re-reading the [contract] and could not find reference to this. I guess I misunderstood something when we had one of our briefs :cold_sweat: 

[contract]: https://drive.google.com/file/d/1SBCHrzCgW6Row7HuGuM4k4nK0kuAwbvv/view?usp=sharing
