### ISSUE TITLE
Check if geonetwork is a viable choice for integrating with geonode

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#44]
We want to provide users with a nice interface for performing CRUD operations on metadata. [geonetwork] seems like a good fit for this job.

However, we need to investigate on the current state of the integration between geonode and geonetwork:

- [ ] Is it still possible to use a geonetwork catalog as a backend to geonode?
- [ ] Is it possible to make this geonetwork catalog be read-write or read-only from the geonode side?

[geonetwork]: https://geonetwork-opensource.org/

**Comment by ricardogsilva** [comment]
@gubuntu 

## Investigation result

Based on my investigation I found out that unfortunately it is currently not possible to integrate geonetwork with geonode in a relevant way for this project.

**It is not possible to create a metadata record on geonetwork and have it appear on geonode.**

### Details

Investigation steps that I took:

-  I've setup a local docker-compose stack by using the [official geonode docker instructions] 
-  Tweaked the `settings.py` file in order to use geonetwork as the metadata catalogue.

   ```python
   # geonode's `settings.py` file
   CATALOGUE = {
        'default': {
            'ENGINE': 'geonode.catalogue.backends.geonetwork',
            'URL': 'http://localhost:8080/geonetwork/srv/eng/csw',
            'USER': 'admin',
            'PASSWORD': 'admin',
        }
   }
   ```
-  Added the following extra configuration for having an extra geonetwork container in the docker stack:

   ```yaml
   # geonode's `docker-compose.override.localhost.yml` file
   geonetwork-catalog:
     image: geonetwork:3.10.2-postgres
     environment:
       POSTGRES_DB_HOST: db
       POSTGRES_DB_NAME: geonode
       POSTGRES_DB_USERNAME: geonode
       POSTGRES_DB_PASSWORD: geonode
     ports:
       - "8080:8080"
   ```

-  Stood up the docker stack

   ```
   docker-compose up -f docker-compose.yml -f docker-compose.override.localhost.yml up --detach
   ```

-  After a while everything was up and running

-  I was able to access geonode on `http://localhost`

-  I was able to access geonetwork on `http://localhost:8080/geonetwork`

-  I was able to check that the geonode settings were being used:

   ```python
   # python shell running inside the geonode-django container
   # this was opened with `docker exec -ti django4geonode python3 manage.py shell`
   In [1]: from django.conf import settings
   In [2]: settings.CATALOGUE
   Out [2]:
   {'default': {'ENGINE': 'geonode.catalogue.backends.geonetwork',
   'URL': 'http://localhost:8080/geonetwork/srv/eng/csw',
   'USER': 'admin',
   'PASSWORD': 'admin'}}   
   ```
-  geonode reported a correct CSW URL on its `developers` section: http://localhost:8080/geonetwork/srv/eng/csw?service=CSW&version=2.0.2&request=GetCapabilities

-  Then I accessed the geonetwork frontend, logged in and added the default templates and sample data - This populated the catalog with 14 records

-  Back on geonode, when accessing the `layers` section, a total of zero layers were found

-  I read [geonode's documentation about existing management commands] in order to understand if some additional synchronization between geonode and geonetwork might be needed in order to the metadata to appear on geonode. Apparently there is no command to do that type of synchronization

-  So it seems that it currently is not possible to have a workflow where a metadata record is created in geonetwork and then it is reflected in the geonode frontend

-  I also tried the other way around: created a geonode layer by using geonode's frontend, added relevant metadata record and then tried to access this layer on geonetwork. This also fails.

   -  layer was correctly created on geonode and showed up in geoserver too
   -  however, the metadata record was not present in geonetwork
  
   
[official geonode docker instructions]: https://docs.geonode.org/en/master/install/advanced/core/index.html#docker
[geonode's documentation about existing management commands]: https://docs.geonode.org/en/master/admin/index.html#geonode-management-commands

**Comment by ricardogsilva** [comment]
I guess this leaves us with limited metadata editing choices:

1. Use geonode's metadata editor, which is fairly basic but seems to work OK

   This means that the original plan of having geonode be just a read-only consumer of the core system needs to be altered. Geonode would become the tool to maintain a published dataset's metadata records.

   This means the metadata profile that we will adopt must match exactly what the geonode frontend is currently able to recognize.

   Personally, given the current restrictions, I think this is the best option.

1. Use geonetwork to create metadata records and then do a manual upload of the generated XML file to geonode

   This seems like a cumbersome process and it would force us to keep two disconnected metadata catalogues (geonode does not seem to be able to support metadata harvesting, even if that is supported by pycsw)

   I'm not in favor of this approach

1. Go back to the drawing board and select another frontend for the project. Some of the alternatives out there:

   -  [geonetwork]
   -  [CKAN]

   Given current project constraints, I am also not in favor of this option either.

1. Some other option?

[geonetwork]: https://geonetwork-opensource.org/
[ckan]: https://ckan.org/

**Comment by timlinux** [comment]
@ricardogsilva I thought there was also a way to connect GeoServer and GeoNetwork together? I wonder if this additional step might be needed to make everything work?

**Comment by timlinux** [comment]
And sticking with PyCSW means we have no way to manage the metadata from QGIS right?

My original hope was that we could hack the GeoCatBridge plugins to let you edit pycsw? But apparently it uses a specific GeoNetwork API - how much work is needed to make it work with PyCSW?

**Comment by ricardogsilva** [comment]
> @ricardogsilva I thought there was also a way to connect GeoServer and GeoNetwork together? I wonder if this additional step might be needed to make everything work?

Apparently there is a way to [connect them] but I'm not clear on what it actually does. 

I will investigate on this and report back.

[connect them]: https://geonetwork-opensource.org/manuals/trunk/en/administrator-guide/configuring-the-catalog/map-server-configuration.html#map-servers-configuration-for-geopublication

**Comment by ricardogsilva** [comment]
@timlinux
I've been further investigating the connection between geonetwork and geoserver. This still does not allow us to fulfill initial requirements though.

**It is not possible to generate a metadata record using geonetwork and have this record appear on geonode automatically.**

IMO we need to decide between:

1. Using geonode as a metadata editor and as a frontend for DomiNode's main web app.

1. Replacing geonode with geonetwork and use it as a metadata editor and as the DomiNode's main web app. This will possibly also unlock editing metadata via QGIS, by leveraging the geocat bridge plugin. @gubuntu How invested is the client in keeping GeoNode as the main frontend for DomiNode? Is this even a realistic possibility for them?


#### Further details

The main issue here is that geonode's current state does not read geonetwork records at all.

In geonode, it is possible to run the `updatelayers` command in order to make geonode recognize existing geoserver layers and sync them in its own DB. But this process does not use geonetwork at all, so layers created in geonode DB and do not pick up any pre-existing metadata that may already exist for the layer in geonetwork - this happens even when geonode is configured to use geonetwork as the catalog and also with geonetwork and geoserver connected to each other.

Geoserver and geonetwork actually integrate in a nice way:

-  I was able to create a new layer in QGIS, then import it into a postgis DB
-  Then in geoserver I published this layer as a wms
-  In geonetwork I was able to create a metadata record of the dataset and link it with the wms service in a clean way
-  geonetwork also has a map section and it allows displaying the wms layer directly on top of it
-  geonetwork also has some powerful metadata editing abilities and a nice permissions model

At this point I think it is not worth continuing investigation on integrating these three applications, as geonode's development seems to have taken a different course over time and is now more dependent on pycsw.

> My original hope was that we could hack the GeoCatBridge plugins to let you edit pycsw? But apparently it uses a specific GeoNetwork API - how much work is needed to make it work with PyCSW?

For GeoCRIS, Samweli had [already estimated] this work to take roughly 28 days. So, given the current time restrictions I think we should look for another solution.



[already estimated]: https://docs.google.com/document/d/19mQL8Xd5ImvSytVH6w1I2K3Yl-t4U4mckSG4GUaDZiQ/edit#heading=h.1otwnkmim5nx

**Comment by timlinux** [comment]
Given your notes above @ricardogsilva I would propose to just mandate that metadata editing should happen on GeoNode - I don't think it is good value to the client to do anything else given the current state of play with the various tools. Let's see what @gubuntu proposes
