### ISSUE TITLE
Bug notes from Charles

### ISSUE THREAD

**Issue by lucernae** [dominodeorg/dominode#46]
Taken from slack message:

I pointed out the following to Gavin in respect of the Dominode:
- [x] the Coat of Arms must be at the top of the page
- [x] the link to the homepage says Geonode instead of Dominode
- [x] Layer thumbnails do not load
- [x] Legend thumbnails do not load
- [x] my credentials don't get passed on to Geoserver from GeoNode (after signing in)
- [x] clicking "View on Site" on Django User Details page sends user to an invalid page (URL is incomplete)

**Comment by lucernae** [comment]
So far the state of the resolved issue:

- We reuse styles and templates from previous dominode.dm taken from https://bitbucket.org/louisca/dominode_production/
- Layer thumbnails and Legend thumbnails not rendering because we changed base url from cuadro.nunez.co into dominode.dm. Migrating the url fix the problem

What is still not working/existing potential issue:
- credentials didn't get passed from GeoNode to GeoServer. There are some issue with the script on upstream GeoNode. We need to patch it if we want it to work with our deployment (https is handled by ingress)
- clicking "View on Site" on Django User Details page sends user to an invalid page (URL is incomplete). Not really sure what happens, this is Django's feature. Maybe there are settings that we missed. Redirect didn't include the base url.
- Thumbnails generated by current geonode seems to be poor in quality.

**Comment by gubuntu** [comment]
Is there a manage.py command for regenerating all thumbnails? Otherwise @ricardogsilva you could assign Seabilwe to rest them manually

**Comment by lucernae** [comment]
I did regenerate layers who doesn't have thumbnails. I've tried both from the interface and executing it directly from the python code. Result are the same. For now, all of the layer's thumbnail are regenerated. 1 layer have white thumbnail because it doesn't have any feature (this layer comes from the training session).
Next approach would be to try to reupload/reimport the layer so the thumbnail regenerated like a fresh layer.

**Comment by ricardogsilva** [comment]
We will be re-ingesting all layers once the production env is up, so any issues with the thumbnails shall eventually be resolved then.

@lucernae what is the status of the issues mentioned above:

> my credentials don't get passed on to Geoserver from GeoNode (after signing in)
> clicking "View on Site" on Django User Details page sends user to an invalid page (URL is incomplete)

Both these work OK on my local env, which unfortunately is still not using k8s (hence #78)

I believe this issue ties in with #47, as I currently do not have a clear picture on how we are applying GeoNode customization stuff in our own envs.

**Comment by lucernae** [comment]
@ricardogsilva 
> my credentials don't get passed on to Geoserver from GeoNode (after signing in)

I submitted a patch to upstream geonode: https://github.com/GeoNode/geonode/pull/6222
But it's not applied to dominode.dm yet

> clicking "View on Site" on Django User Details page sends user to an invalid page (URL is incomplete)
Django thing issues, you need to define the site object for this to work. Fixed in the dominode.dm .

**Comment by ricardogsilva** [comment]
@lucernae 
So I guess this can be closed then?

**Comment by lucernae** [comment]
The credentials are passed, so we can close it.
