### ISSUE TITLE
Design and test workflows for dealing with metadata

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#53]
We need clear workflows for the management of DomiNode metadata. These shall describe how to:

1. Create metadata records for existing datasets
1. Update metadata records
1. Delete metadata records

This information shall be integrated into the [DomiNode data management workflows] document.

Be sure to design, test and describe in the document (similarly to the existing sections) the following aspects:

-  Relevant GeoNode users and groups that must exist and what their access permissions shall be. An initial suggestion:

    -  group `{department}_editor` - Is able to create/edit/delete metadata records for datasets that are owned by its own department. Is able to read all other metadata records.
    -  group `dominode_internal` - Is able to read all metadata records, regardless if they have been made public or not
    -  group `visitor` - Does not need to authenticate and has read-only access to all public datasets - This represents the final enduser

-  Flow of events. An initial suggestion for workflow 1: 

    -  dataset is published on GeoNode by the data custodian and is only accessible to privileged GeoNode users (i.e. those that are part of the relevant `{department}_editor` group) - Example: the `ppd_roads_v1.0.0` resource is published in GeoNode in a way that only users of the `ppd_editors` group are able to create/edit/delete its metadata

    -  metadata custodian proceeds to create and validate the metadata record for the dataset

    -  metadata custodian notifies data custodian that dataset is ready for final publication

    -  data custodian does the final publication

[DomiNode data management workflows]: https://docs.google.com/document/d/1rcoH0c1RpCguuPFLe92V-2xdipJU9ODwItOS_XPe-GM/

**Comment by Samweli** [comment]
@ricardogsilva, I estimate this will take about 1 week.

**Comment by ricardogsilva** [comment]
> @ricardogsilva, I estimate this will take about 1 week.

Then please assign it the correct label, which shall be `size: 13+`

**Comment by ricardogsilva** [comment]
@Samweli 
The work being done in #60 is related to this issue. Be sure to check it out, as I believe it will help with this task

**Comment by Samweli** [comment]
> @Samweli
> The work being done in #60 is related to this issue. Be sure to check it out, as I believe it will help with this task

ok @ricardogsilva
