### ISSUE TITLE
No reference grids for layouts at required scales

### ISSUE THREAD

**Issue by zacharlie** [dominodeorg/dominode#61]
Layouts cannot be made to suit scale specific index grids until this data is made available. In addition, symbologies and map styles cannot be optimised accordingly until the scale and layout has been created.

This issue affects toposheets at all scales other than the 1:50000 map.

**Comment by ricardogsilva** [comment]
I'm waiting for Kendell to send me these reference grids. We discussed this in the last meeting and he committed to sending them. I'll chime in as soon as they land in my inbox

**Comment by ricardogsilva** [comment]
I've received the index files from Nick LaRocque (Kendell's colleague from the LSD department).

Shared them privately with @zacharlie

**Comment by gubuntu** [comment]
why not load into dominode pg and share via that?

**Comment by ricardogsilva** [comment]
@gubuntu 

Because the index files provided by LSD are high-res JPEG files depicting the grid. We were hoping to receive these index sheets as vector files, but that was not the case.

@zacharlie will now need to produce a proper vector sheet index for each scale from this reference material that was supplied by LSD.

**Comment by zacharlie** [comment]
The reference grids have been generated as vectors by utilising the methodology outlined below.

- The supplied high resolution raster images with existing grid indexes were georeferenced in order to create vector data for the represented grids.
- The QGIS "Georeferencer" utility was utilised and images were rectified using the Helmert projection algorithm, with nearest neighbour resampling and EPSG:2002 set as the target CRS.
- 7 Control points were observed manually against an array of map details (in EPSG:2002), including coastline features and road intersections. The same points were adjusted for each image accordingly and were distributed throughout the furthermost extents of the island for adjustment purposes.
- Initial position observations (6) were created by generating a new point feature layer in QGIS and capturing initial positions at the map grid/ graticule intersections. Attributes were assigned to these points using the QGIS Fied Calculator ($x, $y) and these values were collected into a table. The grid starting point positioning was deduced empirically by utilising a rounded average of these positions and the average distance between these positions was determined to be 2000m (easting and northing).
- Vector grids were generated automatically by the QGIS Grid Creation processing utility.
- The top left coordinate for the generated grid was determined to be 448035, 1730000.
- The maximum required grid elements was determined by referencing the raster maps and determined to be 20 (width) by 26 (height). Establishing the bottom right extent of the grid was a matter of multiplying the desired number of grid elements by the expected grid interval and adding (easting) or subtracting (northing) the result from the starting position, i.e. 448035+(20\*grid_interval) and 1730000-(26\*grid_interval). The resulting extent position was determined to be 488035, 1678000.
- The 1:2500 grids were visually determined to be half of one graticule square in height, so were exected to be 1000m in height and 2000m in width. As a result, a 1000x1000m grid was also produced using the same method and extents of the 2000m grid.
- Additionally, a 50m by 50m point feature grid was generated and utilised for snapping purposes.
- Visual inspection of the generated grids across all georeferenced raster sources indicated that the determined starting position and intervals utilised in the grid generation were suitably accurate.
- The 2000m grid vectors were copied to a new index for each relevant scale (1:10000 and 1:5000). The 1000m grid vectors were copied to a new index layer for the 1:2500 index.
- Each index layer was manually processed by removing any grid elements which did not intersect relevant index areas on the corresponding georeferenced image. Automatically generated attribute fields were removed and a single text field was created named 'index'. Each set of grid elements which were visually determined to intersect a corresponding index feature were merged into a single feature, and the underlying attribute value was manually captured into the available 'index' attribute field.
- Where existing features extended beyond the standard extent, the index vector was extended to encompass, as accurately as could reasonably be determined, aligned to the 50m by 50m snapping grid.
- Pseudonodes produced as a side effect of the merging of multiple grid elements were manually removed from all features.

The resulting index grid vectors are currently being utilised for the production of the topomap layouts and will likely be included within the published spatial data infrastructure, however they may also be made available on request.

**Comment by ricardogsilva** [comment]
Seems like a solid work @zacharlie !

Please add these new datasets to the data catalog spreadsheet here:

https://docs.google.com/spreadsheets/d/1uiuey2w4IvCNtNK0rV2Z3e5IOk0TsbGrkQit9Cdic0o/edit#gid=0

Please also add them to the geopackage file that was created earlier and re-upload (leave the link here) so that these become available to others

**Comment by zacharlie** [comment]
Files have been added to data catalogue and included in the existing geopackage, currently available on google drive.

[https://drive.google.com/file/d/1B3o7bPx1iQH5qMXUGWQO-BwLkeJYlYP7/view](https://drive.google.com/file/d/1B3o7bPx1iQH5qMXUGWQO-BwLkeJYlYP7/view?usp=sharing)

**Comment by zacharlie** [comment]
I am attaching the details of the control points utilised for the georeferencing operations in order that users may verify that the vector grid index is suitably matched to the source content.

**_Index_2500_**
Name: 2500_map_sheet_index.jpg
Size: 130665665 bytes (124 MiB)
SHA256: 132AAE2C6A031859EB3CF09F831480A67DED50D3E433B12D67A6FD9851EFD536
**Control**:
```
mapX,mapY,pixelX,pixelY,enable,dX,dY,residual
460960.58529783680569381,1728452.89792710170149803,3739.50589622641655296,-921.17452830188540247,1,18.93988147250138354,0.74918019587084927,18.95469285317718544
456610.62241026118863374,1723396.99933478399179876,2746.77358490565984539,-2115.2818396226407458,1,-10.55143610607046867,5.91717302209008267,12.09734435625597193
460843.58510315587045625,1701189.30557111441157758,3764.99439858490723054,-7365.64946933962164621,1,-4.4398397446520903,-2.18447260082666617,4.94814081266436467
475703.73126593540655449,1717794.7608682147692889,7256.97199292452660302,-3425.48584905660300137,1,-3.61629702261325292,-1.51348090860756201,3.92023323495950304
479543.11199452623259276,1705694.35002613696269691,8177.43410966980081866,-6289.24508033608617552,1,-3.76507589056109282,-10.5673683613895264,11.2180689312813886
466318.97931165847694501,1681523.41157543938606977,5073.13043558368372032,-12001.43515072229092766,1,2.52497564240184147,2.40346324183883553,3.48599161639741117
478339.34625569975469261,1685330.5669253699015826,7910.57661409196953173,-11086.03082620872555708,1,0.90779164899959142,5.19550541159514978,5.27421673425617588

```

**_Index_5000_**
Name: 5000_map_sheet_index.jpg
Size: 127025685 bytes (121 MiB)
SHA256: D2977389B49262E0D60E8571
**Control**:
```
mapX,mapY,pixelX,pixelY,enable,dX,dY,residual
460960.58529783680569381,1728452.89792710170149803,2944.21658805031620432,-696.61229035639496487,1,16.01909306103561903,0.44843104996630245,16.02536841712830551
456610.62241026118863374,1723396.99933478399179876,1947.68815513627077962,-1890.57193396226580262,1,-9.8115869254743302,5.84518569833790025,11.42074576567540767
460843.58510315587045625,1701189.30557111441157758,2966.01755765199413872,-7141.75314465408973774,1,-3.87934573171605734,-2.53952338838098512,4.63664774878549846
475703.73126593540655449,1717794.7608682147692889,6457.22890461216229596,-3199.64884696016861199,1,-1.83169749980879715,-0.18991618445397762,1.84151673571633778
479543.11199452623259276,1705694.35002613696269691,7378.77830188679581624,-6064.33700209643484413,1,-3.07187754379174294,-9.87221289497665566,10.33910146423737153
466318.97931165847694501,1681523.41157543938606977,4275.90946016774614691,-11777.82101677147693408,1,1.3057332151583978,2.24891614437183307,2.60049284820861581
478339.34625569975469261,1685330.5669253699015826,7112.07298218031519355,-10863.40277777775736467,1,1.26968142470195744,4.05911957569696824,4.25306273760916032

```

**_Index_10000_**
Name: 10000_map_sheet_index.jpg
Size: 127267790 bytes (121 MiB)
SHA256: 21CE3E6EF061F79791F8A8B16D13CF60B4BF73328B408F746C7DE7D2E3DF8A35
**Control**:
```
mapX,mapY,pixelX,pixelY,enable,dX,dY,residual
460960.58529783680569381,1728452.89792710170149803,2927.88456498951882168,-667.98637316561905664,1,6.28155106034364508,-1.35567623533597725,6.42617629533761736
456610.62241026118863374,1723396.99933478399179876,1917.4010170990595725,-1858.38465780048659326,1,-6.27498434173503483,6.27914512269035185,8.87711056373783691
460843.58510315587045625,1701189.30557111441157758,2933.82345715409337572,-7109.64156129892035096,1,-3.38301657777356013,-3.16712593413740251,4.63416528062783328
475703.73126593540655449,1717794.7608682147692889,6425.74041863207821734,-3167.53130186496218812,1,0.14753378810110007,3.65317334844712605,3.65615121848588887
479543.11199452623259276,1705694.35002613696269691,7339.16730542453569797,-6035.03061397188048431,1,4.20576398220873671,-9.06044775773716538,9.98900216461728085
466318.97931165847694501,1681523.41157543938606977,4239.29304245284401986,-11748.11851688068600197,1,1.69865028352433001,-1.30368003356124973,2.14126000654370507
478339.34625569975469261,1685330.5669253699015826,7079.57453812895164447,-10832.05703643650304002,1,-2.67549819458872662,4.95461148995673284,5.63084945684563731

```
