### ISSUE TITLE
Topomap graticule intervals and rendering issues

### ISSUE THREAD

**Issue by zacharlie** [dominodeorg/dominode#64]
The intervals for graticule representation at each scale will need to be specified and their styles should be approved.

Currently, there is a possibility that graticule "edges" (which use the zebra-nautical) may display values which overflow the box outline. There does not seem to be a way to mask/ buffer this text in the current LTS release of QGIS and another approach may be required to prevent this.

Whether or not this affects required atlas maps will need to be assessed once the graticule intevals, layouts and required areas have been finalised.

![image](https://user-images.githubusercontent.com/64078329/89029432-bbbe7900-d32e-11ea-80eb-64eabdf3ca80.png)

**Comment by zacharlie** [comment]
The functionality required to fix this issue has been merged into the QGIS master branch.

https://github.com/qgis/QGIS/pull/37662

**Comment by ricardogsilva** [comment]
@zacharlie is this still relevant or can we close it? If so, please go ahead and close this issue

**Comment by zacharlie** [comment]
Although the functionality has been developed, it is not available to my knowledge within the point release and is only in master. It also has not been implemented within the project file. It has a solution, but it can't effectively be implemented until the next LTS release of QGIS.
