### ISSUE TITLE
Allow performing sync of GeoServer layers on GeoNode via GUI

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#81]
Current data management workflows go like this:

a. Dataset is validated
b. Dataset is published on GeoServer
c. GeoNode syncs layers with GeoServer to discover dataset. Layer is created on GeoNode, remaining private
d. Metadata custodian proceeds to generate metadata record
e. GeoNode layer is eventually made public, after metadata generation has been validated

Item c. currently needs to be done by calling geonode's `updatelayers` management command, straight from the GeoNode container's CLI. Incantation is:

```
python manage.py updatelayers \
    --skip-geonode-registered \
    --skip-unadvertised \
    --remove-deleted \
    --workspace {workspace-name} \
    --user {username} \
    --permissions '{"users": {"AnonymousUser: []"}}'
```

**NOTE** - Take special note of the `--permissions` flag. It must be specified like shown in order to make sure that layers are not set to public by default

We won't be allowing endusers to have CLI access to GeoNode container, so we need a way to let relevant users perform this action on the GeoNode web UI.

### Proposed implementation

-  The group page for every `{department}-editor` group shall be augmented with additional UI controls (most likely just a single button) that, when submitted back to the server, shall call the execution of the `updatelayers` command.

-  These new UI elements shall only be visible to users that are members of the specified group and to admins.

**Comment by lucernae** [comment]
This is what I plan for the implementations:

- Add new model in geonode_dominode package that tracks groups that can execute this UI button. The groups can be managed via django admin
- Override the side panel section of the group page so it shows extra menu to sync layers
![image](https://user-images.githubusercontent.com/831865/93188875-b943a180-f76b-11ea-8292-e7e39c69e800.png)
- I assume that we don't use job queue? So is it okay that the sync layers run in the django view thread? That means the web UI will hang/in loading state

**Comment by ricardogsilva** [comment]
@lucernae it would be preferable to use an async queue, since the geoserver sync usually takes quite some time (30+ seconds)

**Comment by ricardogsilva** [comment]
As for the Django implementation, I think creating a new permission shall be enough, it seems having an additional model is not necessary.

I imagine this new permission (let's say it's called `can_sync_geoserver`) to be applied to the content type for layers. It can then be applied to the relevant groups.

https://docs.djangoproject.com/en/3.1/topics/auth/default/#programmatically-creating-permissions

**Comment by ricardogsilva** [comment]
Thinking about it a bit more, I guess the custom permission should be attached to the group model instead of the layer

**Comment by lucernae** [comment]
@ricardogsilva does the async queue uses celery+rabbitmq like that?

> As for the Django implementation, I think creating a new permission shall be enough, it seems having an additional model is not necessary.

Ok, I think we can use permission to associate the command, but won't we still need a model to store the last command result?

**Comment by ricardogsilva** [comment]
@lucernae 

> does the async queue uses celery+rabbitmq like that?

yes I imagine the geoserver sync being done by calling the `updatelayers` admin command from whithin a celery task that would run in a different process and would use rabbitmq as the broker. This means the browser will not be forced to keep a long connection open (and possibly even timeout). This does require an additional notification step though

 > won't we still need a model to store the last command result?

I think persisting execution results in the DB is probably the most robust solution yes. But this will likely take you more effort to implement, as it will also require developing a new view+template for letting the (allowed) users know the execution status in the GeoNode UI.

As a simpler alternative, perhaps you could simply email the user when the celery task is done with the execution result.

Another approach, described [here], is to simply use javascript with some regular polling and update the execution status on the same page, but without persisting it in the DB.

I guess I am fine with whatever approach you decide to use, just so long as it is something that you will be able to implement before the end of this week (this is really the most important factor at the moment)
 
[here]: https://testdriven.io/blog/django-and-celery/

**Comment by ricardogsilva** [comment]
So to summarize, options are:

1. persist execution result in the DB (fronted by an additional django model) plus an additional view/template that group users can inspect in order to check execution results (more effort to implement, but likely best in terms of UX)

2. email user from the celery task, letting him know the result of execution (faster to implement, a bit cumbersome to receive the result via email)

3. some hybrid approach using javascript polling and a task's ID without persisting it in the DB (may be of intermediate implementation complexity, however, probably worst UX, since this won't work if user navigates to a different page)


Personally, I would go with option 2. for now and would later revise to maybe implement option 1., according to available budget.

Do you agree?
