### ISSUE TITLE
Create dominode geonode project

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#82]
Create a [geonode project] for DomiNode.

It shall be used for all our DomiNode-related customizations to GeoNode.

Please follow these directions:

- Name it `geonode_dominode`
- Put it in this repository
- Put the look and feel customizations that were done for #47 in there
- Include a `Dockerfile` for building it

The overall goal to achieve with the completion of this issue is to have a standard GeoNode base for implementing further developments, such as the one described in #81. We shall be able to take the docker image produced by the dockerfile and integrate it together with the other GeoNode components in order to make it possible to deploy DomiNode in a similar way as done currently by the geonode docker spc stack. 

After this is done, follow up with #78 

[geonode project]: https://docs.geonode.org/en/master/install/advanced/project/index.html#geonode-project-installation

**Comment by ricardogsilva** [comment]
@lucernae as for a schedule to get this done, I guess three days would be enough. Do you agree?

**Comment by lucernae** [comment]
Hi @ricardogsilva sorry for not replying. Check my PR here #87

**Comment by lucernae** [comment]
Can we close this then? I've deployed both the Dockerfile recipe and the theme.
