### ISSUE TITLE
Debug performance issues when using QGIS DB Manager to ingest data

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#86]
The planned workflow for ingesting DomiNode vector layers is to use QGIS' DB Manager to import them into the DB as PostGIS layers.

On our **staging environment** this is currently working, but at a very slow speed. 
Here is a test layer:

https://minio.datastore.kartoza.com/public/buildings.gpkg

This layer has building footprints for Roseau (Dominica's capital city). It has 5681 features. Ingesting this layer is taking:

- 16 minutes - Using QGIS DB Manager
- 16 minutes - Using QGIS Browser (drag and drop file into the DB)
- 6 seconds - Using `ogr2ogr` with the following incantation:

  ```
  ogr2ogr \
    -f PostgreSQL \
    -progress \
    -lco OVERWRITE=YES \
    PG:"service='{service-name}'" \
    buildings.gpkg \
    buildings
  ```

SInce `ogr2ogr` is working fine, this seems to be a QGIS issue.

This behavior seems to occur on both QGIS 3.10.8 and QGIS 3.14.0

**Comment by NyakudyaA** [comment]
Can try starting  QGIS without any third-party plugins. There has been some mention of this behavior in the QGIS mailing list recently but it hasn't gained enough traction to be flagged a serious regression i.e http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-db-manager-SQL-console-very-slow-td5441795.html

**Comment by ricardogsilva** [comment]
> Can try starting QGIS without any third-party plugins

Running an import into the `ppd_staging` schema now, after having started qgis with `--noplugins` flag. So far it doesn't seem to make any difference in the upload speed :snail:

**Comment by ricardogsilva** [comment]
My `--nplugins` import took ~18 mins, so it didn't make a difference

**Comment by NyakudyaA** [comment]
Tested with QGIS Master
* Using processing tool (native QGIS algorithm) > 10m with geometry errors reported
* QGIS new profile  with drag and drop  > 30 mins

**Comment by zacharlie** [comment]
Obtained similar results on QGIS 3.14.15-Pi running on a Windows 10 Pro 64-bit system. QGIS was purged and reinstalled last night and currently only uses the default plugins.

- *buildings_cdp_00* took ~34.5 Minutes using the QGIS Browser drag and drop functionality (it should probably be noted) [Database connection using pg_service.conf and https mode set to *allow*]. This function operated in the background and allowed the continued utilisation of QGIS Desktop.
- *buildings_cdp_01* took <10 Seconds using `ogr2ogr -f PostgreSQL -progress PG:"service='{service_name}'" buildings.gpkg {layer_name}` [Using pg_service.conf].
- *buildings_cdp_02* took ~36 minutes using QGIS DB manager import wizard with layer loaded into map [Database connection using pg_service.conf and https mode set to *disable*]. This function operated in the foreground and prevented the continued utilisation of QGIS Desktop.

System resource utilisation was nowhere near feasible maximums when inspected during delayed upload processes (network speed typically between 8-16kbps and went up to about 100 kbps on the odd occasion).

**Comment by timlinux** [comment]
Can you share an image showing the PG Connection dialog? Can you make sure your connection follows the guidelines of Regis here:

**Comment by ricardogsilva** [comment]
@timlinux 

I've just tested and setting the connections options as mentioned in the linked tweet has no impact on this. Importing the layer is still really slow (18 minutes with DB manager, 18 minutes by drag and drop on the QGIS browser panel).

This problem manifests itself on an otherwise pretty empty DB. And the layer being used as a test case is also not very big (less than 6000 features, most of them rectangles, takes less than 2MB of storage when saved as GPKG).

**Comment by timlinux** [comment]
OK thanks for the feedback - I guess it needs to be take upstream to QGIS.

**Comment by ricardogsilva** [comment]
I was able to use the `GDAL -> Vector Miscellaneous -> Export to PostgreSQL (vailable connections)` Processing algorithm to import the sample layer to staging in ~11 seconds.

This Processing algorithm is using `ogr2ogr` underneath.

This means we can readjust our proposed workflow with minimum trouble - QGIS remains the central tool in the ingestion workflow.

We can even create some custom Processing models to improve the ingestion process

With regard to the QGIS native import(s), which are still slow, I think we should raise attention to them in QGIS (at a later date)
